### ISSUE TITLE
Implement Login Page

### ISSUE THREAD

**Issue by kappsegla** [fungover/system2024#17]
Create a login page that integrates with GitHub OAuth.

**Comment by ConnyPettersson** [comment]
A commit was unverified because my email didn't match a verified address on GitHub, blocking the pull request. Attempts to fix this by rebasing caused endless conflicts due to the repository’s history. Instead of continuing to struggle with conflicts, I deleted the problematic branch and will restart the work on a new branch with properly verified commits. This ensures a clean slate without further complications.
